In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.23.2 in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\terranova\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
column_names = ['dir', 'commitId', 'author', 'commitDate']
csvFile = pd.read_csv('output_openstack.csv', delimiter=";", header=None, names=column_names)
csvFile['commitDate'] = pd.to_datetime(csvFile['commitDate'])

In [3]:
csvFile['month_year'] = csvFile['commitDate'].dt.to_period('M')

In [4]:
unique_values = csvFile['dir'].unique()
unique_values

array(['devstack-vagrant', 'puppet-barbican', 'puppet-ceph',
       'puppet-cinder', 'puppet-cloudkitty', 'puppet-designate',
       'puppet-glance', 'puppet-gnocchi', 'puppet-heat', 'puppet-ironic',
       'puppet-magnum', 'puppet-manila', 'puppet-mistral',
       'puppet-octavia', 'puppet-openstack-cookiecutter',
       'puppet-openstack-integration', 'puppet-oslo', 'puppet-placement',
       'puppet-swift', 'puppet-vitrage', 'puppet-watcher', 'puppet-zaqar'],
      dtype=object)

In [5]:
csvFile.head(10)

                dir commitId             author commitDate month_year
0  devstack-vagrant  aa59eb0               Zuul 2023-06-30    2023-06
1  devstack-vagrant  b3acef8               Zuul 2023-06-30    2023-06
2  devstack-vagrant  3155394     Xingjian Zhang 2023-02-27    2023-02
3  devstack-vagrant  0d166a8     Xingjian Zhang 2023-02-27    2023-02
4  devstack-vagrant  8fbf174     Xingjian Zhang 2023-02-27    2023-02
5  devstack-vagrant  8b300b8         Chao Zhang 2020-08-04    2020-08
6  devstack-vagrant  566a3af     Ghanshyam Mann 2020-04-20    2020-04
7  devstack-vagrant  eb992f3        Brian Haley 2019-06-10    2019-06
8  devstack-vagrant  8e6e640  OpenDev Sysadmins 2019-04-19    2019-04
9  devstack-vagrant  e0623b0       Abel Navarro 2017-12-05    2017-12

In [6]:
grouped = csvFile.groupby(['dir', 'month_year']).size().reset_index(name='commits_per_month')

In [7]:
grouped.head(30)

                 dir month_year  commits_per_month
0   devstack-vagrant    2014-02                  6
1   devstack-vagrant    2014-03                 14
2   devstack-vagrant    2014-04                 10
3   devstack-vagrant    2014-05                  6
4   devstack-vagrant    2014-07                  4
5   devstack-vagrant    2014-08                  6
6   devstack-vagrant    2014-09                 20
7   devstack-vagrant    2014-10                  9
8   devstack-vagrant    2014-11                  1
9   devstack-vagrant    2015-01                  2
10  devstack-vagrant    2015-02                  1
11  devstack-vagrant    2015-03                  1
12  devstack-vagrant    2015-04                  1
13  devstack-vagrant    2015-06                  1
14  devstack-vagrant    2015-07                  1
15  devstack-vagrant    2015-09                  4
16  devstack-vagrant    2015-11                  1
17  devstack-vagrant    2015-12                  1
18  devstack-vagrant    2016-07                  2
19  devstack-vagrant    2017-03                  3
20  devstack-vagrant    2017-06                  3
21  devstack-vagrant    2017-12                  1
22  devstack-vagrant    2019-04                  1
23  devstack-vagrant    2019-06                  1
24  devstack-vagrant    2020-04                  1
25  devstack-vagrant    2020-08                  1
26  devstack-vagrant    2023-02                  3
27  devstack-vagrant    2023-06                  2
28   puppet-barbican    2015-10                  5
29   puppet-barbican    2015-11                  4

In [8]:
threshold = 2

# Group by dir and filter out groups where any value in commits_per_month is below the threshold
to_remove = grouped.groupby('dir').filter(lambda x: (x['commits_per_month'] < threshold).any())

# Keep only the groups that don't meet the condition
filtered_grouped = grouped[~grouped['dir'].isin(to_remove['dir'].unique())]

In [9]:
filtered_grouped.head(10)

Empty DataFrame
Columns: [dir, month_year, commits_per_month]
Index: []

In [10]:
unique_values = filtered_grouped['dir'].unique()

print(unique_values)

[]